-- Généré par tools/generate_data.py : ne pas éditer à la main.
local locale = GetLocale()
if locale ~= "deDE" then return end
local _, NS = ...
NS.Tactics = NS.Tactics or {}
local T = NS.Tactics
T[1] = { { "Flüche und Krankheiten", "Etwas, das einen Fluch aufhebt oder eine Krankheit heilt, hilft sehr. Sonst ein leichter Kampf: Säubere den Raum, bevor du ihn angehst." } }
T[2] = { { "Der Beschwörer", "Töte zuerst den Beschwörer: Er ruft Verstärkung. Danach den Elementar." }, { "Feuer überall", "Flächenschaden auf die Gruppe, schlimmer, wenn die Gruppe viel im Nahkampf kämpft." } }
T[3] = { { "Quer durch den Raum geschleudert", "Er schleudert Spieler quer durch den Raum. Säubere die nächsten Gruppen und tanke ihn nahe am Tunnel, damit niemand in einer anderen Gruppe landet." } }
T[4] = { { "Furcht bei schwindendem Leben", "Wenn sein Leben sinkt, versetzt er die ganze Gruppe in Furcht. Plane etwas ein, um sie zu brechen, oder säubere vorher den Raum, damit niemand in andere Gegner rennt." }, { "Die verschlossenen Gewölbe", "Öffne nach dem Kampf die Gewölbe des Raums: etwa 24 Dwarven Heirlooms für Important Heirlooms und die Tafel von The Treaty of Understanding." } }
T[5] = { { "Feuernova", "Feuerschaden an allen in seiner Nähe, mehrmals pro Kampf. Als Heiler: Halte den Nahkampf bei vollem Leben." }, { "Aufwärtshaken", "Ein heftiger Schlag, der den Tank wegstößt." } }
T[6] = { { "Feuerbrand", "Verbrennt einen Spieler, dann alle paar Sekunden Feuerschaden für 21 Sekunden. Unterbrich den Zauber oder bann das Brennen." }, { "Fluch der Schwäche", "Verringert den körperlichen Schaden eines Spielers für 30 Sekunden. Ein Magier oder Druide kann ihn entfernen." } }
T[7] = { { "Spalten", "Trifft sein Ziel und den Spieler, der ihm am nächsten steht." } }
T[8] = { { "Gift", "Seine Schläge vergiften: Naturschaden über Zeit. Heile das Gift, wenn du kannst." }, { "Heimtückischer Angriff", "Zusätzlicher Schaden auf den Tank alle 5 bis 15 Sekunden." } }
T[9] = { { "Die Spinnen im Hof", "Nichts Besonderes am Boss selbst. Säubere zuerst die anderen Spinnen im Hof, sonst schließen sie sich dem Kampf an." } }
T[10] = { note = "Säubere den Hof, klick auf die Statue und halte während der Wellen durch: Sie kommt danach.", { "Frostnova", "Frostschaden auf die ganze Gruppe. Wenn du heilst, spar Mana für alle Wellen." } }
T[11] = { { "In die Luft geschleudert", "Schleudert den Tank in die Luft und betäubt ihn 5 Sekunden lang. Achte als Schadensverursacher auf die Bedrohung: Der Tank hält ihn nur etwa den halben Kampf." }, { "Eine Patrouille", "Säubere seinen Raum, bevor du ihn angehst: Eine Patrouille kommt dort vorbei. Sein Kopf wird für die Quests Abominable Creatures und Unending Torment aufgesammelt." } }
T[12] = { { "Flammenschock", "Sein Hauptzauber. Er kann unterbrochen und betäubt werden: Koordiniere Unterbrechungen und Betäubungen mit der Gruppe." }, { "Viele Lebenspunkte", "Der längste Kampf des Dungeons. Unterbrich bis zum Schluss weiter." } }
T[13] = { note = "Säubere das Haus und die Statue, klick auf den Kamin und halte während der Wellen durch. Er kommt nach dem letzten Fleischgolem.", { "Gift", "Vergiftet sein Ziel. Behalte die Lebensbalken im Auge." }, { "Kräftige Schläge", "Er haut hart zu: Halte den Tank am Leben. Plane Manatränke für die Wellen vor ihm ein." } }
T[14] = { { "Zurückstoßen", "Er stößt zurück: Säubere zuerst die Gruppen um ihn herum, sonst landest du in einer davon." }, { "Antimagieschild", "Schützt sich eine Weile vor Zaubern." }, { "Kräftige Schläge", "Er haut hart zu: Halte den Tank bei vollem Leben." } }
T[15] = { { "Blitzschlag", "Er hält Abstand, um ihn zu wirken. Unterbrich ihn." }, { "Heilende Berührung", "Heilt sich oder einen Verbündeten (3 Sekunden Zauberzeit). Unterbrich ihn." }, { "Cobrahns Schlangengestalt", "Bei 30 % Leben verwandelt er sich in eine Schlange: langsamere, aber schwerere Schläge, und er beginnt, Spieler einzuschläfern." } }
T[16] = { { "Heilende Berührung", "Heilt sich oder einen Verbündeten. Unterbrich sie." }, { "Schlaf", "Versetzt einen Spieler bis zu 20 Sekunden lang in Schlaf. Schaden weckt ihn, und Magie bannen entfernt ihn." }, { "Dornenaura", "Naturschaden an jedem, der sie im Nahkampf schlägt." } }
T[17] = { { "Panzerschild", "12 Sekunden lang erleidet er 60 % weniger Schaden und greift langsamer, aber härter an." } }
T[18] = { { "Donnerschlag", "Naturschaden an allen in seiner Nähe, dann 10 Sekunden lang verlangsamte Angriffe und Bewegungen." }, { "Heilende Berührung", "Heilt sich oder einen Verbündeten. Unterbrich ihn." }, { "Schlaf", "Versetzt einen Spieler bis zu 20 Sekunden lang in Schlaf." } }
T[19] = { { "Kettenblitz", "Ein Blitz, der auf einen zweiten Spieler überspringt. Unterbrich ihn." } }
T[20] = { { "Heilende Berührung", "Eine langsame Heilung (3,5 Sekunden) auf sich oder einen Verbündeten. Unterbrich ihn." }, { "Schlaf", "Versetzt einen Spieler bis zu 20 Sekunden lang in Schlaf." }, { "Blitzschlag", "Er hält Abstand, um ihn zu wirken. Unterbrich ihn." } }
T[21] = { { "Packende Ranken", "Wenn sein Ziel nah ist, wirft er alle in seiner Nähe um und hält sie 10 Sekunden lang fest. Bleib auf Abstand, wenn du weit weg bist." } }
T[22] = { note = "Töte Lady Anacondra, Lord Cobrahn, Lord Pythas und Lord Serpentis, sprich dann am Eingang mit Naralex' Schüler und eskortiere ihn zu Naralex. Beschütze ihn während des Rituals: Mutanus kommt am Ende.", { "Donnerknall", "Naturschaden an allen in seiner Nähe und eine Betäubung von 2,5 Sekunden." }, { "Naralex' Alptraum", "Versetzt einen Spieler bis zu 15 Sekunden lang in Schlaf." }, { "Schrecken", "Lässt einen Spieler 4 Sekunden lang in Furcht fliehen." } }
T[23] = { { "Rhahk'Zors Schlag", "Schlägt den Tank hart und betäubt ihn 3 Sekunden lang." } }
T[24] = { { "Rüstung durchbohren", "Verringert die Rüstung des Tanks 20 Sekunden lang um 75 %." }, { "Flieht um Hilfe", "Bei 15 % Leben flieht er, um Hilfe zu holen. Erledige ihn, bevor er sich entfernt." } }
T[25] = { note = "Er steuert Sneeds Schredder und steigt aus, wenn dieser zerstört wird.", { "Entwaffnen", "Entwaffnet den Tank für 6 Sekunden." } }
T[26] = { { "Schrecken", "Lässt einen Spieler 4 Sekunden lang in Furcht fliehen." }, { "Lähmender Schmerz", "Verlangsamt das Zaubern eines Spielers 15 Sekunden lang um 35 %." } }
T[27] = { { "Geschmolzenes Metall", "Feuerschaden alle 3 Sekunden für 15 Sekunden, mit verlangsamten Angriffen und Bewegungen. Unterbrich die Zauberzeit von 2 Sekunden." } }
T[28] = { { "Heftiges Stampfen", "Bei 66 % und dann bei 33 % Leben betäubt er alle um sich herum und geht dann zu seiner Truhe, um die Waffen zu wechseln." }, { "Verprügeln", "Mit seinen zwei Äxten, ab 66 % Leben: zusätzliche Angriffe auf den Tank." }, { "Mächtiger Schlag", "Mit seinem Hammer, unter 33 % Leben: ein heftiger Schlag, der den Tank 3 Sekunden lang betäubt." } }
T[29] = { { "Vergifteter Harpunenspeer", "Eine Zauberzeit von 2 Sekunden: ein Treffer, dann eine Minute lang Naturschaden. Heile das Gift." }, { "Spalten", "Trifft sein Ziel und den Spieler, der ihm am nächsten steht." } }
T[30] = { { "Zweimal zuschlagen", "Gelegentlich zwei Zusatzangriffe: harte Treffer auf den Tank." }, { "VanCleefs Verbündete", "Bei der Hälfte seines Lebens ruft er zwei Defias-Schurken." } }
T[31] = { { "Säurespritzer", "Naturschaden alle 5 Sekunden für 30 Sekunden an allen in seiner Nähe." }, { "Kochkünste", "Unter der Hälfte seines Lebens heilt er sich (2 Sekunden Zauberzeit). Unterbrich ihn." }, { "Flieht um Hilfe", "Bei 15 % Leben flieht er, um Hilfe zu holen. Erledige ihn, bevor er sich entfernt." } }
T[32] = { { "Seelenentzug", "Hält einen Spieler 10 Sekunden lang fest und entzieht ihm Leben, um sich zu heilen. Unterbrich die Zauberzeit von 2 Sekunden oder bann ihn." } }
T[33] = { { "Verdrehter Schlag", "Das Teufelsross betäubt alle in seiner Nähe für 3 Sekunden, und sie erleiden mehr körperlichen Schaden. Das Schattenross hat keine Fähigkeit." } }
T[34] = { { "Entzug des Schlächters", "Entzieht seinem Ziel im Nahkampf 350 Mana: Ein Tank mit Mana spürt es." } }
T[35] = { { "Schleier der Schatten", "Verflucht einen Spieler: Die Heilung, die er erhält, ist 15 Sekunden lang um 75 % schwächer. Entferne ihn, vor allem beim Tank." } }
T[36] = { { "Heiliges Licht", "Heilt sich oder einen Verbündeten (2,5 Sekunden Zauberzeit). Unterbrich ihn." }, { "Gottesschild", "Macht ihn 10 Sekunden lang immun gegen allen Schaden und alle Zauber." }, { "Hammer der Gerechtigkeit", "Betäubt einen Spieler für 4 Sekunden." } }
T[37] = { { "Ruft um Hilfe", "Wenn du ihn angreifst, ruft er die Kreaturen im Umkreis von 30 Metern. Säubere vorher die Umgebung." }, { "Heulende Wut", "Bei 60 %, 40 % und 20 % Leben werden seine Schläge stärker." } }
T[38] = { { "Spalten", "Trifft sein Ziel und den Spieler, der ihm am nächsten steht." }, { "Kniesehne", "Verlangsamt die Bewegung seines Ziels für 10 Sekunden." } }
T[39] = { note = "Sie kommen zu viert, nachdem Fenrus der Verschlinger gestorben ist: Arugal erscheint kurz und ruft sie.", { "Dunkles Opfer", "Heilt einen anderen Leerwandler. Tötet sie nacheinander." } }
T[40] = { { "Giftiger Speichel", "Naturschaden alle 6 Sekunden und Manaentzug, 2 Minuten lang. Heile das Gift." } }
T[41] = { { "Worgs zur Verstärkung", "Je länger der Kampf dauert, desto mehr Worgs hat er bei sich: nach 30 bis 45 Sekunden ein blasser Worg, dann ein schäumender Worg, dann ein Wolfsschrecken." } }
T[42] = { { "Leerenblitz", "Ein 3 Sekunden langer Schattenblitz auf den Tank, immer wieder. Unterbrich ihn." }, { "Arugals Fluch", "Verwandelt einen Spieler, der nicht der Tank ist, für 10 Sekunden in einen Shadowfang-Vielfraß, der für ihn kämpft. Entferne den Fluch." }, { "Schattenschritt", "Er teleportiert sich zwischen seinem Sims, dem oberen Sims und der Treppe." }, { "Donnerschlag", "Wenn der Tank bei ihm ankommt: Naturschaden und eine Betäubung von 5 Sekunden um ihn herum." } }
T[43] = { { "Zertrampeln", "Trifft alle, die in seiner Nähe stehen." } }
T[44] = { { "Gegabelter Blitz", "Naturschaden in einem Kegel vor ihr (2 Sekunden Zauberzeit). Bleib aus dem Kegel." }, { "Frostnova", "Friert alle in ihrer Nähe bis zu 8 Sekunden lang fest." }, { "Verlangsamen", "Verlangsamt Bewegung und Angriffe eines Spielers für 10 Sekunden." } }
T[45] = { { "Netz", "Hält einen Spieler 10 Sekunden lang an Ort und Stelle fest." } }
T[46] = { note = "Klick auf den Stein der Brasse im Wasser: Er taucht daraus auf.", { "Frostblitz", "Er hält Abstand, um ihn zu wirken: Frostschaden und Verlangsamung." }, { "Frostnova", "Hält alle in seiner Nähe bis zu 8 Sekunden lang fest." } }
T[47] = { { "Schlaf", "Versetzt alle in seiner Nähe bis zu 10 Sekunden lang in Schlaf. Schaden weckt einen Schläfer auf." }, { "Gedankenschlag", "Schattenschaden auf einen Spieler (1,5 Sekunden Zauberzeit)." } }
T[48] = { note = "Er wartet in einer Unterwasserhöhle unter dem Tempel von Twilight Lord Kelris, und viele Gruppen verpassen ihn. Schwimm unter den Tempel, um ihn zu erreichen." }
T[49] = { note = "Sobald Twilight Lord Kelris tot ist, entzünde nacheinander die vier Feuer von Aku'mai in seinem Raum. Jedes bringt eine Welle von Kreaturen. Wenn alle tot sind, öffnet sich Aku'mais Tür.", { "Giftwolke", "Naturschaden alle 5 Sekunden für 45 Sekunden an allen in der Nähe." }, { "Rasende Wut", "Unter 30 % Leben: immer wieder Angriffssalven, die 75 % schneller sind." } }
T[50] = { { "Blitzschild", "Der Blitz trifft jeden, der ihn berührt. Ein Priester oder Schamane kann es entfernen." }, { "Blitzschlag", "Er hält Abstand, um ihn zu wirken. Unterbrich ihn." } }
T[51] = { { "Schildschlag", "Schlägt den Tank und betäubt ihn 2 Sekunden lang." }, { "Flieht um Hilfe", "Bei 15 % Leben flieht er, um Hilfe zu holen. Erledige ihn, bevor er sich entfernt." } }
T[52] = { { "Flieht um Hilfe", "Bei 15 % Leben flieht er, um Hilfe zu holen. Erledige ihn, bevor er sich entfernt." } }
T[53] = { { "Zweimal zuschlagen", "Gelegentlich zwei Zusatzangriffe: harte Treffer auf den Tank." }, { "Wutanfall", "Bei 30 % Leben greift er bis zum Ende des Kampfes 30 % schneller an." } }
T[54] = { { "Kettenblitzschlag", "Ein Blitz, der von Spieler zu Spieler springt (2 Sekunden Zauberzeit). Unterbrich ihn." }, { "Blutrausch", "Beschleunigt seine Angriffe oder die eines Verbündeten 30 Sekunden lang um 30 %. Ein Priester oder Schamane kann ihn entfernen." } }
T[55] = { { "Rauchbombe", "Betäubt alle in seiner Nähe für 4 Sekunden." }, { "Schlachtruf", "Mehr Angriffskraft für ihn und seine Verbündeten für 2 Minuten." }, { "Flieht um Hilfe", "Bei 15 % Leben flieht er, um Hilfe zu holen. Erledige ihn, bevor er sich entfernt." } }
T[56] = { { "Netz", "Hält alle in seiner Nähe 10 Sekunden lang fest." }, { "Verlangsamen", "Verlangsamt Angriffe und Bewegung eines Spielers für 10 Sekunden und kann ihn betäuben." }, { "Mechanische Schabe beschwören", "Ruft mechanische Schaben. Sein Update tötet sie und heilt ihn." } }
T[57] = { note = "Sprich mit Sprengmeisterin Emi Shortfuse und beschütze sie, während sie die beiden Höhleneingänge sprengt. Troggs kommen in Wellen, dann erscheint Grubbis mit Chomper." }
T[58] = { { "Megavolt", "Naturschaden in einem Kegel vor ihm (2 Sekunden Zauberzeit). Nur der Tank steht davor." }, { "Kettenblitzschlag", "Ein Blitz, der auf Spieler in der Nähe überspringt (2,5 Sekunden Zauberzeit). Unterbrich ihn." } }
T[59] = { { "Niedermähen", "Trifft alle in seiner Nähe und unterbricht ihre Zauber. Zauberer und Heiler, haltet Abstand." }, { "Kegelförmiger Schlag", "Trifft alle in einem Kegel vor ihm." }, { "Zertrampeln", "Trifft alle, die in seiner Nähe stehen." } }
T[60] = { { "Flammendiener beschwören", "Ruft zu Beginn des Kampfes zwei Flammendiener." }, { "Feuerball", "Er hält Abstand, um ihn zu wirken. Unterbrich ihn." }, { "Feuerschild II", "Feuerschaden an allen in seiner Nähe für eine Minute. Ein Priester oder Schamane kann es entfernen." } }
T[61] = { { "Laufende Bomben", "Er entzündet nacheinander die Gnomenköpfe rund um den Raum, und jeder lässt laufende Bomben los, die beim Erreichen eines Spielers explodieren. Der Knopf neben einem Kopf schaltet ihn aus. Unter der Hälfte seines Lebens entzündet er sie schneller." }, { "Wegstoßen", "Stößt den Tank weg. Unter der Hälfte seines Lebens trifft es alle um ihn herum." } }
