-- Généré par tools/generate_data.py : ne pas éditer à la main.
local locale = GetLocale()
if locale ~= "esES" and locale ~= "esMX" then return end
local _, NS = ...
NS.Tactics = NS.Tactics or {}
local T = NS.Tactics
T[1] = { { "Maldiciones y enfermedades", "Ayuda llevar algo para eliminar una maldición o curar una enfermedad. Por lo demás, un combate fácil: limpia la sala antes de iniciarlo." } }
T[2] = { { "El invocador", "Mata primero al invocador: trae refuerzos. Después, al elemental." }, { "Fuego por todas partes", "Daño de área al grupo, peor cuando el grupo pelea mucho cuerpo a cuerpo." } }
T[3] = { { "Lanzado por la sala", "Lanza por los aires a los jugadores por la sala. Limpia los grupos más cercanos y tanquéalo cerca del túnel, para que nadie caiga en otro grupo." } }
T[4] = { { "Miedo al debilitarse", "Cuando baja su salud, aterroriza a todo el grupo. Prepara algo para romperlo, o limpia la sala antes para que nadie corra hacia otros enemigos." }, { "Las cámaras cerradas", "Tras el combate, abre las cámaras de la sala: unos 24 Dwarven Heirlooms para Important Heirlooms, y la tablilla de The Treaty of Understanding." } }
T[5] = { { "Nova de fuego", "Daño de Fuego a todos los que estén cerca de él, varias veces por combate. Como sanador, mantén con la salud llena al cuerpo a cuerpo." }, { "Gancho", "Un golpe fuerte que empuja al tanque." } }
T[6] = { { "Inmolar", "Quema a un jugador, y luego daño de Fuego cada pocos segundos durante 21 segundos. Interrumpe el hechizo o disipa la quemadura." }, { "Maldición de debilidad", "Reduce el daño físico de un jugador durante 30 segundos. Un mago o un druida puede quitarla." } }
T[7] = { { "Hendedura", "Golpea a su objetivo y al jugador más cercano a este." } }
T[8] = { { "Veneno", "Sus golpes envenenan: daño de Naturaleza con el tiempo. Cura el veneno si puedes." }, { "Ataque insidioso", "Daño adicional al tanque cada 5 a 15 segundos." } }
T[9] = { { "Las arañas del patio", "Nada especial en el jefe en sí. Limpia primero las otras arañas del patio, o se unirán al combate." } }
T[10] = { note = "Limpia el patio, haz clic en la estatua y aguanta durante las oleadas: aparece después.", { "Nova de escarcha", "Daño de escarcha a todo el grupo. Si sanas, guarda maná para todas las oleadas." } }
T[11] = { { "Lanzado por los aires", "Lanza al tanque por los aires y lo aturde 5 segundos. Ojo con la amenaza del daño: el tanque solo lo mantiene aproximadamente la mitad del combate." }, { "Una patrulla", "Limpia su sala antes de iniciar el combate: pasa una patrulla por allí. Su cabeza se recoge para las misiones Abominable Creatures y Unending Torment." } }
T[12] = { { "Choque de llamas", "Su hechizo principal. Se le puede interrumpir y aturdir: organiza las interrupciones y los aturdimientos con el grupo." }, { "Muchos puntos de salud", "El combate más largo de la mazmorra. Sigue interrumpiendo hasta el final." } }
T[13] = { note = "Limpia la casa y la estatua, haz clic en la chimenea y aguanta durante las oleadas. Llega después del último gólem de carne.", { "Veneno", "Envenena a su objetivo. Vigila las barras de salud." }, { "Golpes poderosos", "Pega fuerte: mantén vivo al tanque. Prepara pociones de maná para las oleadas anteriores a él." } }
T[14] = { { "Empujón", "Empuja: limpia primero los grupos que lo rodean, o aterrizarás en uno de ellos." }, { "Escudo antimagia", "Se protege un rato contra los hechizos." }, { "Golpes poderosos", "Pega fuerte: mantén al tanque con la salud llena." } }
T[15] = { { "Descarga de relámpagos", "Mantiene la distancia para lanzarla. Interrúmpelo." }, { "Toque de sanación", "Se cura a sí mismo o a un aliado (lanzamiento de 3 segundos). Interrúmpelo." }, { "Forma de serpiente de Cobrahn", "Al 30% de salud, se transforma en serpiente: golpes más lentos pero más pesados, y empieza a dormir a jugadores." } }
T[16] = { { "Toque de sanación", "Se cura a sí misma o a un aliado. Interrúmpela." }, { "Dormir", "Duerme a un jugador hasta 20 segundos. El daño lo despierta, y disipar magia lo libera." }, { "Aura de espinas", "Daño de Naturaleza a quien la golpee cuerpo a cuerpo." } }
T[17] = { { "Caparazón escudo", "Durante 12 segundos, recibe un 60% menos de daño y ataca más lento pero más fuerte." } }
T[18] = { { "Atronar", "Daño de Naturaleza a todos los que estén cerca de él, y luego ataques y movimiento ralentizados durante 10 segundos." }, { "Toque de sanación", "Se cura a sí mismo o a un aliado. Interrúmpelo." }, { "Dormir", "Duerme a un jugador hasta 20 segundos." } }
T[19] = { { "Relámpagos en cadena", "Un rayo que rebota en un segundo jugador. Interrúmpelo." } }
T[20] = { { "Toque de sanación", "Una curación lenta (3,5 segundos) sobre sí mismo o un aliado. Interrúmpelo." }, { "Dormir", "Duerme a un jugador hasta 20 segundos." }, { "Descarga de relámpagos", "Mantiene la distancia para lanzarla. Interrúmpelo." } }
T[21] = { { "Enredaderas ávidas", "Cuando su objetivo está cerca, derriba e inmoviliza a todos los que estén cerca de él durante 10 segundos. A distancia, mantente lejos." } }
T[22] = { note = "Mata a Dama Anacondra, al Señor Cobrahn, al Señor Pythas y al Señor Serpentis, luego habla con el discípulo de Naralex en la entrada y escóltalo hasta Naralex. Protégelo durante el ritual: Mutanus llega al final.", { "Estruendo de trueno", "Daño de Naturaleza a todos los que estén cerca de él y un aturdimiento de 2,5 segundos." }, { "Pesadilla de Naralex", "Duerme a un jugador hasta 15 segundos." }, { "Aterrorizar", "Hace huir de miedo a un jugador durante 4 segundos." } }
T[23] = { { "Golpe de Rhahk'Zor", "Golpea fuerte al tanque y lo aturde 3 segundos." } }
T[24] = { { "Perforar armadura", "Reduce la armadura del tanque un 75% durante 20 segundos." }, { "Huye a buscar ayuda", "Al 15% de salud, huye a buscar ayuda. Remátalo antes de que se aleje." } }
T[25] = { note = "Pilota la Trituradora de Sneed y sale de ella cuando la destruyen.", { "Desarmar", "Desarma al tanque durante 6 segundos." } }
T[26] = { { "Aterrorizar", "Hace huir de miedo a un jugador durante 4 segundos." }, { "Dolor abrumador", "Reduce la velocidad de lanzamiento de un jugador un 35% durante 15 segundos." } }
T[27] = { { "Metal fundido", "Daño de Fuego cada 3 segundos durante 15 segundos, con ataques y movimiento ralentizados. Interrumpe el lanzamiento de 2 segundos." } }
T[28] = { { "Pisotón violento", "Al 66% y luego al 33% de salud, aturde a todos los que tiene alrededor y va a su cofre a cambiar de armas." }, { "Aporrear", "Con sus dos hachas, desde el 66% de salud: ataques adicionales sobre el tanque." }, { "Poderoso bofetón", "Con su martillo, por debajo del 33% de salud: un golpe fuerte que aturde al tanque 3 segundos." } }
T[29] = { { "Arpón envenenado", "Un lanzamiento de 2 segundos: un golpe y después daño de Naturaleza durante un minuto. Cura el veneno." }, { "Hendedura", "Golpea a su objetivo y al jugador más cercano a este." } }
T[30] = { { "Aporrear", "De vez en cuando, dos ataques adicionales: golpes fuertes sobre el tanque." }, { "Aliados de VanCleef", "A la mitad de su salud, llama a dos pícaros defias." } }
T[31] = { { "Salpicadura de ácido", "Daño de Naturaleza cada 5 segundos durante 30 segundos a todos los que estén cerca de él." }, { "Cocina de Cookie", "Por debajo de la mitad de su salud, se cura (lanzamiento de 2 segundos). Interrúmpelo." }, { "Huye a buscar ayuda", "Al 15% de salud, huye a buscar ayuda. Remátalo antes de que se aleje." } }
T[32] = { { "Drenar alma", "Inmoviliza a un jugador 10 segundos y le drena la salud para curarse. Interrumpe el lanzamiento de 2 segundos o disípalo." } }
T[33] = { { "Golpe retorcido", "El corcel vil aturde a todos los que estén cerca de él durante 3 segundos, y reciben más daño físico. El corcel de sombra no tiene ninguna técnica." } }
T[34] = { { "Drenaje del carnicero", "Drena 350 puntos de maná a su objetivo en cuerpo a cuerpo: un tanque con maná lo nota." } }
T[35] = { { "Velo de sombras", "Maldice a un jugador: las curaciones que recibe son un 75% menores durante 15 segundos. Quítala, sobre todo al tanque." } }
T[36] = { { "Luz sagrada", "Se cura a sí mismo o a un aliado (lanzamiento de 2,5 segundos). Interrúmpelo." }, { "Escudo divino", "Lo vuelve inmune a todo el daño y a todos los hechizos durante 10 segundos." }, { "Martillo de justicia", "Aturde a un jugador durante 4 segundos." } }
T[37] = { { "Pide ayuda", "Al iniciar el combate, llama a las criaturas a menos de 30 metros. Limpia a su alrededor antes." }, { "Rabia aullante", "Al 60%, 40% y 20% de salud, sus golpes se vuelven más fuertes." } }
T[38] = { { "Hendedura", "Golpea a su objetivo y al jugador más cercano a este." }, { "Desjarretar", "Reduce la velocidad de movimiento de su objetivo durante 10 segundos." } }
T[39] = { note = "Llegan de cuatro en cuatro tras la muerte de Fenrus el Devorador: Arugal aparece un instante y los llama.", { "Ofrenda oscura", "Cura a otro abisario. Matadlos de uno en uno." } }
T[40] = { { "Baba tóxica", "Daño de Naturaleza cada 6 segundos y maná drenado, durante 2 minutos. Cura el veneno." } }
T[41] = { { "Huargos de refuerzo", "Cuanto más dura el combate, más huargos tiene con él: un huargo pálido a los 30 a 45 segundos, luego un huargo espumeante y después un horror lupino." } }
T[42] = { { "Descarga del Vacío", "Un virote de Sombras de 3 segundos sobre el tanque, una y otra vez. Interrúmpelo." }, { "Maldición de Arugal", "Convierte a un jugador que no sea el tanque en un Glotón Colmillo Oscuro que lucha por él durante 10 segundos. Quita la maldición." }, { "Puerto de las Sombras", "Se teletransporta entre su saliente, el saliente de arriba y la escalera." }, { "Choque de trueno", "Cuando el tanque llega hasta él: daño de Naturaleza y un aturdimiento de 5 segundos a su alrededor." } }
T[43] = { { "Pisotón", "Golpea a todos los que estén cerca de él." } }
T[44] = { { "Rayo bifurcado", "Daño de Naturaleza en un cono frente a ella (lanzamiento de 2 segundos). Quédate fuera del cono." }, { "Nova de escarcha", "Congela en el sitio a todos los que estén cerca de ella hasta 8 segundos." }, { "Ralentizar", "Reduce la velocidad de movimiento y de ataque de un jugador durante 10 segundos." } }
T[45] = { { "Red", "Inmoviliza a un jugador en el sitio durante 10 segundos." } }
T[46] = { note = "Haz clic en la piedra de la Brasse en el agua: sale de ella.", { "Descarga de escarcha", "Mantiene la distancia para lanzarla: daño de Escarcha y ralentización." }, { "Nova de escarcha", "Inmoviliza a todos los que estén cerca de él hasta 8 segundos." } }
T[47] = { { "Dormir", "Duerme a todos los que estén cerca de él hasta 10 segundos. El daño despierta al que duerme." }, { "Explosión mental", "Daño de Sombras a un jugador (lanzamiento de 1,5 segundos)." } }
T[48] = { note = "Espera en una cueva bajo el agua, debajo del templo del Señor del Crepúsculo Kelris, y muchos grupos se lo pierden. Nada bajo el templo para llegar hasta él." }
T[49] = { note = "Con el Señor del Crepúsculo Kelris muerto, enciende uno tras otro los cuatro fuegos de Aku'mai de su sala. Cada uno trae una oleada de criaturas. Cuando están todas muertas, se abre la puerta de Aku'mai.", { "Nube venenosa", "Daño de Naturaleza cada 5 segundos durante 45 segundos a todos los que estén cerca." }, { "Rabia frenética", "Por debajo del 30% de salud: ráfagas de ataques un 75% más rápidos, una y otra vez." } }
T[50] = { { "Escudo de relámpagos", "El rayo golpea a quien lo toque. Un sacerdote o un chamán puede quitárselo." }, { "Descarga de relámpagos", "Mantiene la distancia para lanzarla. Interrúmpelo." } }
T[51] = { { "Azote con escudo", "Golpea al tanque y lo aturde 2 segundos." }, { "Huye a buscar ayuda", "Al 15% de salud, huye a buscar ayuda. Remátalo antes de que se aleje." } }
T[52] = { { "Huye a buscar ayuda", "Al 15% de salud, huye a buscar ayuda. Remátalo antes de que se aleje." } }
T[53] = { { "Aporrear", "De vez en cuando, dos ataques adicionales: golpes fuertes sobre el tanque." }, { "Enfurecer", "Al 30% de salud, ataca un 30% más rápido hasta el final del combate." } }
T[54] = { { "Cadena de relámpagos", "Un rayo que rebota de jugador en jugador (lanzamiento de 2 segundos). Interrúmpelo." }, { "Sed de sangre", "Acelera sus ataques o los de un aliado un 30% durante 30 segundos. Un sacerdote o un chamán puede quitarla." } }
T[55] = { { "Bomba de humo", "Aturde a todos los que estén cerca de él durante 4 segundos." }, { "Grito de batalla", "Más poder de ataque para él y sus aliados durante 2 minutos." }, { "Huye a buscar ayuda", "Al 15% de salud, huye a buscar ayuda. Remátalo antes de que se aleje." } }
T[56] = { { "Red", "Inmoviliza a todos los que estén cerca de él durante 10 segundos." }, { "Ralentización", "Reduce la velocidad de ataque y de movimiento de un jugador durante 10 segundos, y puede aturdirlo." }, { "Invocar cucaracha mecánica", "Llama a cucarachas mecánicas. Su Actualización las mata y lo cura." } }
T[57] = { note = "Habla con la maestra dinamitera Emi Mechacorta y protégela mientras vuela las dos entradas de la cueva. Llegan troggs en oleadas y después viene Grubbis con Chomper." }
T[58] = { { "Megavoltio", "Daño de Naturaleza en un cono frente a él (lanzamiento de 2 segundos). Solo el tanque se pone delante." }, { "Cadena de relámpagos", "Un rayo que rebota entre los jugadores cercanos (lanzamiento de 2,5 segundos). Interrúmpelo." } }
T[59] = { { "Segar a la multitud", "Golpea a todos los que estén cerca de él e interrumpe sus hechizos. Lanzadores y sanadores, manteneos a distancia." }, { "Golpe en arco", "Golpea a todos en un cono frente a él." }, { "Pisotón", "Golpea a todos los que estén cerca de él." } }
T[60] = { { "Invocar sirviente de fuego", "Llama a dos sirvientes de fuego al empezar el combate." }, { "Bola de fuego", "Mantiene la distancia para lanzarla. Interrúmpelo." }, { "Escudo de fuego II", "Daño de Fuego a todos los que estén cerca de él durante un minuto. Un sacerdote o un chamán puede quitárselo." } }
T[61] = { { "Bombas andantes", "Va encendiendo una a una las cabezas de gnomo alrededor de la sala, y cada una suelta bombas andantes que explotan al llegar a un jugador. El botón junto a una cabeza la apaga. Por debajo de la mitad de su salud, las enciende más rápido." }, { "Empujar", "Empuja al tanque. Por debajo de la mitad de su salud, alcanza a todos los que tiene alrededor." } }
