-- Généré par tools/generate_data.py : ne pas éditer à la main.
local locale = GetLocale()
if locale ~= "frFR" then return end
local _, NS = ...
NS.Tactics = NS.Tactics or {}
local T = NS.Tactics
T[1] = { { "Malédictions et maladies", "De quoi lever une malédiction ou guérir une maladie aide bien. Sinon un combat facile : nettoie la salle avant de l’engager." } }
T[2] = { { "L’invocateur", "Tue d’abord l’invocateur : il fait venir des renforts. Ensuite l’élémentaire." }, { "Du feu partout", "Des dégâts de zone sur le groupe, pires quand le groupe se bat beaucoup au corps à corps." } }
T[3] = { { "Envoyé à travers la salle", "Il envoie valser les joueurs dans la salle. Nettoie les groupes les plus proches et tanke-le près du tunnel, pour que personne n’atterrisse dans un autre groupe." } }
T[4] = { { "Peur quand il faiblit", "Quand sa vie baisse, il terrifie tout le groupe. Prévois de quoi la briser, ou nettoie la salle avant pour que personne ne fonce dans d’autres ennemis." }, { "Les caveaux fermés", "Après le combat, ouvre les caveaux de la salle : environ 24 Dwarven Heirlooms pour Important Heirlooms, et la tablette de The Treaty of Understanding." } }
T[5] = { { "Nova de feu", "Des dégâts de Feu à tous ceux qui sont près de lui, plusieurs fois par combat. Côté soins, garde le corps à corps plein de vie." }, { "Uppercut", "Un coup violent qui repousse le tank." } }
T[6] = { { "Immolation", "Brûle un joueur, puis des dégâts de Feu toutes les quelques secondes pendant 21 secondes. Interromps le sort ou dissipe la brûlure." }, { "Malédiction de faiblesse", "Réduit les dégâts physiques d’un joueur pendant 30 secondes. Un mage ou un druide peut la retirer." } }
T[7] = { { "Enchaînement", "Frappe sa cible et le joueur le plus proche d’elle." } }
T[8] = { { "Poison", "Ses coups empoisonnent : des dégâts de Nature sur la durée. Guéris le poison si tu peux." }, { "Attaque pernicieuse", "Des dégâts en plus sur le tank toutes les 5 à 15 secondes." } }
T[9] = { { "Les araignées de la cour", "Rien de spécial sur le boss lui-même. Nettoie d’abord les autres araignées de la cour, sinon elles rejoignent le combat." } }
T[10] = { note = "Nettoie la cour, clique sur la statue et tiens bon pendant les vagues : elle arrive après.", { "Nova de givre", "Dégâts de givre sur tout le groupe. Si tu soignes, garde du mana pour toutes les vagues." } }
T[11] = { { "Projeté en l’air", "Projette le tank en l’air et l’étourdit 5 secondes. Attention à la menace côté dégâts : le tank ne le tient qu’environ la moitié du combat." }, { "Une patrouille", "Nettoie sa salle avant de l’engager : une patrouille passe par là. Sa tête se ramasse pour les quêtes Abominable Creatures et Unending Torment." } }
T[12] = { { "Choc de flammes", "Son sort principal. Il peut être interrompu et étourdi : organise les interruptions et les étourdissements avec le groupe." }, { "Beaucoup de points de vie", "Le combat le plus long du donjon. Continue les interruptions jusqu’au bout." } }
T[13] = { note = "Nettoie la maison et la statue, clique sur la cheminée et tiens bon pendant les vagues. Il arrive après le dernier golem de chair.", { "Poison", "Empoisonne sa cible. Surveille les barres de vie." }, { "Coups puissants", "Il tape fort : garde le tank en vie. Prévois des potions de mana pour les vagues avant lui." } }
T[14] = { { "Repoussement", "Il repousse : nettoie d’abord les groupes autour de lui, sinon tu atterris dans l’un d’eux." }, { "Bouclier antimagie", "Se protège un moment contre les sorts." }, { "Coups puissants", "Il tape fort : garde le tank plein de vie." } }
T[15] = { { "Eclair", "Il garde ses distances pour le lancer. Interromps-le." }, { "Toucher guérisseur", "Se soigne ou soigne un allié (incantation de 3 secondes). Interromps-le." }, { "Forme de serpent de Cobrahn", "À 30 % de vie, il se change en serpent : des coups plus lents mais plus lourds, et il commence à endormir des joueurs." } }
T[16] = { { "Toucher guérisseur", "Se soigne ou soigne un allié. Interromps-la." }, { "Sommeil", "Endort un joueur jusqu’à 20 secondes. Des dégâts le réveillent, et une dissipation de la magie l’enlève." }, { "Aura d’épines", "Des dégâts de Nature à quiconque la frappe au corps à corps." } }
T[17] = { { "Carapace bouclier", "Pendant 12 secondes, il subit 60 % de dégâts en moins et attaque plus lentement mais plus fort." } }
T[18] = { { "Coup de tonnerre", "Des dégâts de Nature à tous ceux qui sont près de lui, puis attaques et déplacements ralentis pendant 10 secondes." }, { "Toucher guérisseur", "Se soigne ou soigne un allié. Interromps-le." }, { "Sommeil", "Endort un joueur jusqu’à 20 secondes." } }
T[19] = { { "Eclairs en série", "Un éclair qui rebondit sur un deuxième joueur. Interromps-le." } }
T[20] = { { "Toucher guérisseur", "Un soin lent (3,5 secondes) sur lui ou un allié. Interromps-le." }, { "Sommeil", "Endort un joueur jusqu’à 20 secondes." }, { "Eclair", "Il garde ses distances pour le lancer. Interromps-le." } }
T[21] = { { "Lianes avides", "Quand sa cible est proche, il renverse et immobilise tous ceux qui sont près de lui pendant 10 secondes. À distance, garde tes distances." } }
T[22] = { note = "Tue Dame Anacondra, le Seigneur Cobrahn, le Seigneur Pythas et le Seigneur Serpentis, puis parle au disciple de Naralex à l’entrée et escorte-le jusqu’à Naralex. Protège-le pendant le rituel : Mutanus arrive à la fin.", { "Fracas du tonnerre", "Des dégâts de Nature à tous ceux qui sont près de lui et un étourdissement de 2,5 secondes." }, { "Cauchemar de Naralex", "Endort un joueur jusqu’à 15 secondes." }, { "Terrifier", "Fait fuir un joueur de peur pendant 4 secondes." } }
T[23] = { { "Frappe de Rhahk'Zor", "Frappe fort le tank et l’étourdit 3 secondes." } }
T[24] = { { "Perce-armure", "Réduit l’armure du tank de 75 % pendant 20 secondes." }, { "Fuit chercher de l’aide", "À 15 % de vie, il s’enfuit chercher de l’aide. Achève-le avant qu’il ne s’éloigne." } }
T[25] = { note = "Il pilote le Déchiqueteur de Sneed et en sort quand il est détruit.", { "Désarmement", "Désarme le tank pendant 6 secondes." } }
T[26] = { { "Terrifier", "Fait fuir un joueur de peur pendant 4 secondes." }, { "Douleur accablante", "Ralentit les incantations d’un joueur de 35 % pendant 15 secondes." } }
T[27] = { { "Métal en fusion", "Des dégâts de Feu toutes les 3 secondes pendant 15 secondes, avec attaques et déplacements ralentis. Interromps l’incantation de 2 secondes." } }
T[28] = { { "Martèlement violent", "À 66 % puis à 33 % de vie, il étourdit tout le monde autour de lui, puis va à son coffre changer d’armes." }, { "Rosser", "Avec ses deux haches, dès 66 % de vie : des attaques en plus sur le tank." }, { "Puissant soufflet", "Avec son marteau, sous 33 % de vie : un coup violent qui étourdit le tank 3 secondes." } }
T[29] = { { "Harpon empoisonné", "Une incantation de 2 secondes : un coup, puis des dégâts de Nature pendant une minute. Guéris le poison." }, { "Enchaînement", "Frappe sa cible et le joueur le plus proche d’elle." } }
T[30] = { { "Rosser", "De temps en temps, deux attaques en plus : de gros coups sur le tank." }, { "Alliés de VanCleef", "À la moitié de sa vie, il appelle deux canailles défias." } }
T[31] = { { "Jet d’acide", "Des dégâts de Nature toutes les 5 secondes pendant 30 secondes à tous ceux qui sont près de lui." }, { "Cuisine de Macaron", "Sous la moitié de sa vie, il se soigne (incantation de 2 secondes). Interromps-le." }, { "Fuit chercher de l’aide", "À 15 % de vie, il s’enfuit chercher de l’aide. Achève-le avant qu’il ne s’éloigne." } }
T[32] = { { "Drain d’âme", "Immobilise un joueur 10 secondes et lui draine sa vie pour se soigner. Interromps l’incantation de 2 secondes ou dissipe-le." } }
T[33] = { { "Coup tordu", "Le palefroi corrompu étourdit tous ceux qui sont près de lui pendant 3 secondes, et ils subissent plus de dégâts physiques. Le destrier des ténèbres n’a aucune technique." } }
T[34] = { { "Drain du boucher", "Draine 350 points de mana à sa cible au corps à corps : un tank qui a du mana le sent passer." } }
T[35] = { { "Voile de l'ombre", "Maudit un joueur : les soins qu’il reçoit sont 75 % plus faibles pendant 15 secondes. Retire-la, surtout sur le tank." } }
T[36] = { { "Lumière sacrée", "Se soigne ou soigne un allié (incantation de 2,5 secondes). Interromps-le." }, { "Bouclier divin", "Le rend insensible à tous les dégâts et à tous les sorts pendant 10 secondes." }, { "Marteau de la justice", "Étourdit un joueur pendant 4 secondes." } }
T[37] = { { "Appelle à l’aide", "Quand tu l’engages, il appelle les créatures à moins de 30 mètres. Nettoie autour de lui avant." }, { "Rage hurlante", "À 60 %, 40 % et 20 % de vie, ses coups deviennent plus forts." } }
T[38] = { { "Enchaînement", "Frappe sa cible et le joueur le plus proche d’elle." }, { "Brise-genou", "Ralentit les déplacements de sa cible pendant 10 secondes." } }
T[39] = { note = "Ils arrivent à quatre après la mort de Fenrus le Dévoreur : Arugal apparaît un instant et les appelle.", { "Sombre offrande", "Soigne un autre marcheur du Vide. Tuez-les un par un." } }
T[40] = { { "Bave toxique", "Des dégâts de Nature toutes les 6 secondes et du mana drainé, pendant 2 minutes. Guéris le poison." } }
T[41] = { { "Des worgs en renfort", "Plus le combat dure, plus il a de worgs avec lui : un worg pâle au bout de 30 à 45 secondes, puis un worg écumant, puis une horreur lupine." } }
T[42] = { { "Eclair de Vide", "Un trait d’Ombre de 3 secondes sur le tank, encore et encore. Interromps-le." }, { "Malédiction d’Arugal", "Change un joueur autre que le tank en Glouton d’Ombrecroc qui se bat pour lui pendant 10 secondes. Retire la malédiction." }, { "Port de l'ombre", "Il se téléporte entre son rebord, le rebord du haut et l’escalier." }, { "Coup de Tonnerre", "Quand le tank arrive sur lui : des dégâts de Nature et un étourdissement de 5 secondes autour de lui." } }
T[43] = { { "Piétiner", "Frappe tous ceux qui se tiennent près de lui." } }
T[44] = { { "Fourche d'éclairs", "Des dégâts de Nature dans un cône devant elle (incantation de 2 secondes). Reste hors du cône." }, { "Nova de givre", "Gèle sur place tous ceux qui sont près d’elle jusqu’à 8 secondes." }, { "Lenteur", "Ralentit les déplacements et les attaques d’un joueur pendant 10 secondes." } }
T[45] = { { "Filet", "Immobilise un joueur sur place pendant 10 secondes." } }
T[46] = { note = "Clique sur la pierre de la Brasse dans l’eau : il en surgit.", { "Eclair de givre", "Il garde ses distances pour le lancer : des dégâts de Givre et un ralentissement." }, { "Nova de givre", "Immobilise tous ceux qui sont près de lui jusqu’à 8 secondes." } }
T[47] = { { "Sommeil", "Endort tous ceux qui sont près de lui jusqu’à 10 secondes. Des dégâts réveillent un dormeur." }, { "Attaque mentale", "Des dégâts d’Ombre sur un joueur (incantation de 1,5 seconde)." } }
T[48] = { note = "Il attend dans une grotte sous l’eau, sous le temple du Seigneur du Crépuscule Kelris, et beaucoup de groupes le ratent. Nage sous le temple pour l’atteindre." }
T[49] = { note = "Une fois le Seigneur du Crépuscule Kelris mort, allume les quatre feux d’Aku’mai de sa salle, l’un après l’autre. Chacun amène une vague de créatures. Quand elles sont toutes mortes, la porte d’Aku’mai s’ouvre.", { "Nuage empoisonné", "Des dégâts de Nature toutes les 5 secondes pendant 45 secondes à tous ceux qui sont proches." }, { "Rage frénétique", "Sous 30 % de vie : des rafales d’attaques 75 % plus rapides, encore et encore." } }
T[50] = { { "Bouclier de foudre", "La foudre frappe quiconque le touche. Un prêtre ou un chaman peut le retirer." }, { "Eclair", "Il garde ses distances pour le lancer. Interromps-le." } }
T[51] = { { "Heurt de bouclier", "Frappe le tank et l’étourdit 2 secondes." }, { "Fuit chercher de l’aide", "À 15 % de vie, il s’enfuit chercher de l’aide. Achève-le avant qu’il ne s’éloigne." } }
T[52] = { { "Fuit chercher de l’aide", "À 15 % de vie, il s’enfuit chercher de l’aide. Achève-le avant qu’il ne s’éloigne." } }
T[53] = { { "Rosser", "De temps en temps, deux attaques en plus : de gros coups sur le tank." }, { "Enrager", "À 30 % de vie, il attaque 30 % plus vite jusqu’à la fin du combat." } }
T[54] = { { "Chaîne d'éclairs", "Un éclair qui rebondit de joueur en joueur (incantation de 2 secondes). Interromps-le." }, { "Furie sanguinaire", "Accélère ses attaques ou celles d’un allié de 30 % pendant 30 secondes. Un prêtre ou un chaman peut la retirer." } }
T[55] = { { "Bombe fumigène", "Étourdit tous ceux qui sont près de lui pendant 4 secondes." }, { "Cri de guerre", "Plus de puissance d’attaque pour lui et ses alliés pendant 2 minutes." }, { "Fuit chercher de l’aide", "À 15 % de vie, il s’enfuit chercher de l’aide. Achève-le avant qu’il ne s’éloigne." } }
T[56] = { { "Filet", "Immobilise tous ceux qui sont près de lui pendant 10 secondes." }, { "Ralentissement", "Ralentit les attaques et les déplacements d’un joueur pendant 10 secondes, et peut l’étourdir." }, { "Invocation d'une blatte mécanique", "Appelle des blattes mécaniques. Sa Mise à jour les tue et le soigne." } }
T[57] = { note = "Parle au maître-dynamiteur Emi Courtemèche et protège-la pendant qu’elle fait sauter les deux entrées de grotte. Des troggs arrivent par vagues, puis Grubbis vient avec Mâchouilleur." }
T[58] = { { "Mégavolt", "Des dégâts de Nature dans un cône devant lui (incantation de 2 secondes). Seul le tank se met devant." }, { "Chaîne d'éclairs", "Un éclair qui rebondit sur les joueurs proches (incantation de 2,5 secondes). Interromps-le." } }
T[59] = { { "Faucher la foule", "Frappe tous ceux qui sont près de lui et interrompt leurs sorts. Lanceurs de sorts et soigneurs, gardez vos distances." }, { "Frappe en arc de cercle", "Frappe tout le monde dans un cône devant lui." }, { "Piétiner", "Frappe tous ceux qui se tiennent près de lui." } }
T[60] = { { "Invocation d'un serviteur enflammé", "Appelle deux serviteurs enflammés au début du combat." }, { "Boule de feu", "Il garde ses distances pour le lancer. Interromps-le." }, { "Bouclier de feu II", "Des dégâts de Feu à tous ceux qui sont près de lui pendant une minute. Un prêtre ou un chaman peut le retirer." } }
T[61] = { { "Bombes ambulantes", "Il allume une à une les têtes de gnome autour de la salle, et chacune lâche des bombes ambulantes qui explosent en atteignant un joueur. Le bouton à côté d’une tête l’éteint. Sous la moitié de sa vie, il les allume plus vite." }, { "Repousser au loin", "Repousse le tank. Sous la moitié de sa vie, cela touche tout le monde autour de lui." } }
