-- Généré par tools/generate_data.py : ne pas éditer à la main.
local locale = GetLocale()
if locale ~= "itIT" then return end
local _, NS = ...
NS.Tactics = NS.Tactics or {}
local T = NS.Tactics
T[1] = { { "Maledizioni e malattie", "Qualcosa per rimuovere una maledizione o curare una malattia aiuta parecchio. Per il resto è un combattimento facile: ripulisci la sala prima di ingaggiarlo." } }
T[2] = { { "L'evocatore", "Uccidi prima l'evocatore: fa arrivare rinforzi. Poi l'elementale." }, { "Fuoco ovunque", "Danni ad area sul gruppo, peggiori quando il gruppo combatte molto in mischia." } }
T[3] = { { "Scagliato attraverso la sala", "Scaglia i giocatori per la sala. Ripulisci i gruppi più vicini e tienilo con il difensore vicino al tunnel, così nessuno atterra in un altro gruppo." } }
T[4] = { { "Paura quando si indebolisce", "Quando la sua salute cala, terrorizza tutto il gruppo. Prevedi di che spezzarla, oppure ripulisci prima la sala così nessuno corre addosso ad altri nemici." }, { "I forzieri chiusi", "Dopo il combattimento, apri i forzieri della sala: circa 24 Dwarven Heirlooms per Important Heirlooms, e la tavoletta di The Treaty of Understanding." } }
T[5] = { { "Nova di fuoco", "Danni da Fuoco a tutti quelli che gli sono vicino, più volte per combattimento. Per i guaritori: tieni in piena salute chi combatte in mischia." }, { "Montante", "Un colpo violento che respinge il difensore." } }
T[6] = { { "Immolazione", "Brucia un giocatore, poi danni da Fuoco ogni pochi secondi per 21 secondi. Interrompi l'incantesimo o dissolvi la bruciatura." }, { "Maledizione della debolezza", "Riduce i danni fisici di un giocatore per 30 secondi. Un mago o un druido può rimuoverla." } }
T[7] = { { "Fendente", "Colpisce il suo bersaglio e il giocatore più vicino a esso." } }
T[8] = { { "Veleno", "I suoi colpi avvelenano: danni da Natura nel tempo. Cura il veleno se puoi." }, { "Attacco insidioso", "Danni aggiuntivi sul difensore ogni 5-15 secondi." } }
T[9] = { { "I ragni del cortile", "Niente di speciale sul boss stesso. Ripulisci prima gli altri ragni del cortile, altrimenti si uniscono al combattimento." } }
T[10] = { note = "Ripulisci il cortile, clicca sulla statua e tieni duro durante le ondate: arriva dopo.", { "Nova di gelo", "Danni da gelo su tutto il gruppo. Se curi, tieni del mana per tutte le ondate." } }
T[11] = { { "Scagliato in aria", "Scaglia il difensore in aria e lo stordisce per 5 secondi. Attenzione alla minaccia dei danneggiatori: il difensore lo tiene solo per circa metà del combattimento." }, { "Una pattuglia", "Ripulisci la sua sala prima di ingaggiarlo: passa una pattuglia. La sua testa si raccoglie per le missioni Abominable Creatures e Unending Torment." } }
T[12] = { { "Shock di fiamma", "Il suo incantesimo principale. Può essere interrotto e stordito: organizza interruzioni e stordimenti con il gruppo." }, { "Tanti punti salute", "Il combattimento più lungo del dungeon. Continua a interrompere fino alla fine." } }
T[13] = { note = "Ripulisci la casa e la statua, clicca sul camino e tieni duro durante le ondate. Arriva dopo l'ultimo golem di carne.", { "Veleno", "Avvelena il suo bersaglio. Tieni d'occhio le barre della salute." }, { "Colpi potenti", "Picchia forte: tieni in vita il difensore. Prevedi pozioni di mana per le ondate prima di lui." } }
T[14] = { { "Respingimento", "Respinge: ripulisci prima i gruppi intorno a lui, altrimenti atterri in uno di essi." }, { "Scudo anti-magia", "Si protegge per un po' contro gli incantesimi." }, { "Colpi potenti", "Picchia forte: tieni il difensore in piena salute." } }
T[15] = { { "Fulmine", "Resta a distanza per lanciarlo. Interrompilo." }, { "Tocco curativo", "Cura sé stesso o un alleato (lancio di 3 secondi). Interrompilo." }, { "Forma di serpente di Cobrahn", "Al 30% di salute, si trasforma in serpente: colpi più lenti ma più pesanti, e comincia ad addormentare i giocatori." } }
T[16] = { { "Tocco curativo", "Cura sé stessa o un alleato. Interrompila." }, { "Sonno", "Addormenta un giocatore fino a 20 secondi. I danni lo svegliano, e un Dissolvi magia lo rimuove." }, { "Aura di spine", "Danni da Natura a chiunque la colpisca in mischia." } }
T[17] = { { "Guscio scudo", "Per 12 secondi, subisce il 60% di danni in meno e attacca più lentamente ma più forte." } }
T[18] = { { "Tuono", "Danni da Natura a tutti quelli che gli sono vicino, poi attacchi e movimenti rallentati per 10 secondi." }, { "Tocco curativo", "Cura sé stesso o un alleato. Interrompilo." }, { "Sonno", "Addormenta un giocatore fino a 20 secondi." } }
T[19] = { { "Fulmini in serie", "Un fulmine che rimbalza su un secondo giocatore. Interrompilo." } }
T[20] = { { "Tocco curativo", "Una cura lenta (3,5 secondi) su di lui o su un alleato. Interrompilo." }, { "Sonno", "Addormenta un giocatore fino a 20 secondi." }, { "Fulmine", "Resta a distanza per lanciarlo. Interrompilo." } }
T[21] = { { "Rampicanti avidi", "Quando il suo bersaglio è vicino, atterra e immobilizza tutti quelli che gli sono vicino per 10 secondi. Se è a distanza, mantieni le distanze." } }
T[22] = { note = "Uccidi Lady Anacondra, Lord Cobrahn, Lord Pythas e Lord Serpentis, poi parla con il discepolo di Naralex all'ingresso e scortalo fino a Naralex. Proteggilo durante il rituale: Mutanus arriva alla fine.", { "Calpestio del tuono", "Danni da Natura a tutti quelli che gli sono vicino e uno stordimento di 2,5 secondi." }, { "Incubo di Naralex", "Addormenta un giocatore fino a 15 secondi." }, { "Terrorizzare", "Fa fuggire un giocatore in preda al terrore per 4 secondi." } }
T[23] = { { "Colpo di Rhahk'Zor", "Colpisce forte il difensore e lo stordisce per 3 secondi." } }
T[24] = { { "Perforare l'armatura", "Riduce l'armatura del difensore del 75% per 20 secondi." }, { "Fugge a cercare aiuto", "Al 15% di salute, fugge a cercare aiuto. Finiscilo prima che si allontani." } }
T[25] = { note = "Pilota lo Sneed's Shredder e ne esce quando viene distrutto.", { "Disarmare", "Disarma il difensore per 6 secondi." } }
T[26] = { { "Terrorizzare", "Fa fuggire un giocatore in preda al terrore per 4 secondi." }, { "Dolore opprimente", "Rallenta i lanci di un giocatore del 35% per 15 secondi." } }
T[27] = { { "Metallo fuso", "Danni da Fuoco ogni 3 secondi per 15 secondi, con attacchi e movimenti rallentati. Interrompi il lancio di 2 secondi." } }
T[28] = { { "Martellata violenta", "Al 66% e poi al 33% di salute, stordisce tutti quelli intorno a lui, poi va al suo forziere a cambiare armi." }, { "Percuotere", "Con le sue due asce, dal 66% di salute: attacchi aggiuntivi sul difensore." }, { "Potente schiaffo", "Con il suo martello, sotto il 33% di salute: un colpo violento che stordisce il difensore per 3 secondi." } }
T[29] = { { "Arpione avvelenato", "Un lancio di 2 secondi: un colpo, poi danni da Natura per un minuto. Cura il veleno." }, { "Fendente", "Colpisce il suo bersaglio e il giocatore più vicino a esso." } }
T[30] = { { "Percuotere", "Ogni tanto, due attacchi aggiuntivi: grossi colpi sul difensore." }, { "Alleati di VanCleef", "A metà salute, chiama due furfanti Defias." } }
T[31] = { { "Getto d'acido", "Danni da Natura ogni 5 secondi per 30 secondi a tutti quelli che gli sono vicino." }, { "Cucina di Cookie", "Sotto metà salute, si cura (lancio di 2 secondi). Interrompilo." }, { "Fugge a cercare aiuto", "Al 15% di salute, fugge a cercare aiuto. Finiscilo prima che si allontani." } }
T[32] = { { "Risucchio d'anima", "Immobilizza un giocatore per 10 secondi e ne risucchia la salute per curarsi. Interrompi il lancio di 2 secondi o dissolvilo." } }
T[33] = { { "Colpo storto", "Il destriero corrotto stordisce tutti quelli che gli sono vicino per 3 secondi, e subiscono più danni fisici. Il destriero oscuro non ha nessuna tecnica." } }
T[34] = { { "Risucchio del macellaio", "Risucchia 350 punti di mana al suo bersaglio in mischia: un difensore con del mana se ne accorge." } }
T[35] = { { "Velo d'ombra", "Maledice un giocatore: le cure che riceve sono più deboli del 75% per 15 secondi. Rimuovila, soprattutto dal difensore." } }
T[36] = { { "Luce sacra", "Cura sé stesso o un alleato (lancio di 2,5 secondi). Interrompilo." }, { "Scudo divino", "Lo rende immune a tutti i danni e a tutti gli incantesimi per 10 secondi." }, { "Martello della giustizia", "Stordisce un giocatore per 4 secondi." } }
T[37] = { { "Chiama aiuto", "Quando lo ingaggi, chiama le creature entro 30 metri. Ripulisci prima intorno a lui." }, { "Rabbia ululante", "Al 60%, 40% e 20% di salute, i suoi colpi diventano più forti." } }
T[38] = { { "Fendente", "Colpisce il suo bersaglio e il giocatore più vicino a esso." }, { "Spezzaginocchio", "Rallenta i movimenti del suo bersaglio per 10 secondi." } }
T[39] = { note = "Arrivano in quattro dopo la morte di Fenrus il Divoratore: Arugal appare per un istante e li chiama.", { "Offerta oscura", "Cura un altro Camminatore del Vuoto. Uccideteli uno alla volta." } }
T[40] = { { "Bava tossica", "Danni da Natura ogni 6 secondi e mana risucchiato, per 2 minuti. Cura il veleno." } }
T[41] = { { "Worg di rinforzo", "Più il combattimento dura, più worg ha con sé: un worg pallido dopo 30-45 secondi, poi un worg schiumante, poi un orrore lupino." } }
T[42] = { { "Dardo del Vuoto", "Un dardo d'Ombra di 3 secondi sul difensore, ancora e ancora. Interrompilo." }, { "Maledizione di Arugal", "Trasforma un giocatore che non è il difensore in un Shadowfang Glutton che combatte per lui per 10 secondi. Rimuovi la maledizione." }, { "Passo d'ombra", "Si teletrasporta tra il suo cornicione, il cornicione in alto e la scalinata." }, { "Schianto del tuono", "Quando il difensore lo raggiunge: danni da Natura e uno stordimento di 5 secondi intorno a lui." } }
T[43] = { { "Calpestare", "Colpisce tutti quelli che gli stanno vicino." } }
T[44] = { { "Fulmine biforcuto", "Danni da Natura in un cono davanti a lei (lancio di 2 secondi). Stai fuori dal cono." }, { "Nova di gelo", "Congela sul posto tutti quelli che le sono vicino fino a 8 secondi." }, { "Lentezza", "Rallenta i movimenti e gli attacchi di un giocatore per 10 secondi." } }
T[45] = { { "Rete", "Immobilizza un giocatore sul posto per 10 secondi." } }
T[46] = { note = "Clicca sulla Fathom Stone nell'acqua: ne emerge.", { "Dardo di gelo", "Resta a distanza per lanciarlo: danni da Gelo e rallentamento." }, { "Nova di gelo", "Immobilizza tutti quelli che gli sono vicino fino a 8 secondi." } }
T[47] = { { "Sonno", "Addormenta tutti quelli che gli sono vicino fino a 10 secondi. I danni svegliano chi dorme." }, { "Attacco mentale", "Danni da Ombra a un giocatore (lancio di 1,5 secondi)." } }
T[48] = { note = "Aspetta in una grotta sott'acqua, sotto il tempio del Signore del Crepuscolo Kelris, e molti gruppi lo mancano. Nuota sotto il tempio per raggiungerlo." }
T[49] = { note = "Dopo la morte del Signore del Crepuscolo Kelris, accendi uno dopo l'altro i quattro fuochi di Aku'mai nella sua sala. Ognuno porta un'ondata di creature. Quando sono tutte morte, la porta di Aku'mai si apre.", { "Nube velenosa", "Danni da Natura ogni 5 secondi per 45 secondi a tutti quelli vicini." }, { "Rabbia frenetica", "Sotto il 30% di salute: raffiche di attacchi più veloci del 75%, ancora e ancora." } }
T[50] = { { "Scudo di fulmini", "Il fulmine colpisce chiunque lo tocchi. Un sacerdote o uno sciamano può rimuoverlo." }, { "Fulmine", "Resta a distanza per lanciarlo. Interrompilo." } }
T[51] = { { "Colpo di scudo", "Colpisce il difensore e lo stordisce per 2 secondi." }, { "Fugge a cercare aiuto", "Al 15% di salute, fugge a cercare aiuto. Finiscilo prima che si allontani." } }
T[52] = { { "Fugge a cercare aiuto", "Al 15% di salute, fugge a cercare aiuto. Finiscilo prima che si allontani." } }
T[53] = { { "Percuotere", "Ogni tanto, due attacchi aggiuntivi: grossi colpi sul difensore." }, { "Infuriare", "Al 30% di salute, attacca il 30% più veloce fino alla fine del combattimento." } }
T[54] = { { "Catena di fulmini", "Un fulmine che rimbalza da giocatore a giocatore (lancio di 2 secondi). Interrompilo." }, { "Brama di sangue", "Accelera i suoi attacchi o quelli di un alleato del 30% per 30 secondi. Un sacerdote o uno sciamano può rimuoverla." } }
T[55] = { { "Bomba fumogena", "Stordisce tutti quelli che gli sono vicino per 4 secondi." }, { "Grido di battaglia", "Più potenza d'attacco per lui e i suoi alleati per 2 minuti." }, { "Fugge a cercare aiuto", "Al 15% di salute, fugge a cercare aiuto. Finiscilo prima che si allontani." } }
T[56] = { { "Rete", "Immobilizza tutti quelli che gli sono vicino per 10 secondi." }, { "Rallentamento", "Rallenta gli attacchi e i movimenti di un giocatore per 10 secondi e può stordirlo." }, { "Evocazione di uno scarafaggio meccanico", "Chiama degli scarafaggi meccanici. Il suo Aggiornamento li uccide e lo cura." } }
T[57] = { note = "Parla con l'artificiere Emi Shortfuse e proteggila mentre fa saltare le due entrate delle grotte. I trogg arrivano a ondate, poi Grubbis arriva con Chomper." }
T[58] = { { "Megavolt", "Danni da Natura in un cono davanti a lui (lancio di 2 secondi). Solo il difensore si mette davanti." }, { "Catena di fulmini", "Un fulmine che rimbalza sui giocatori vicini (lancio di 2,5 secondi). Interrompilo." } }
T[59] = { { "Falciare la folla", "Colpisce tutti quelli che gli sono vicino e interrompe i loro incantesimi. Incantatori e guaritori, state a distanza." }, { "Colpo ad arco", "Colpisce tutti in un cono davanti a lui." }, { "Calpestare", "Colpisce tutti quelli che gli stanno vicino." } }
T[60] = { { "Evocazione di un servitore infuocato", "Chiama due servitori infuocati all'inizio del combattimento." }, { "Palla di fuoco", "Resta a distanza per lanciarla. Interrompilo." }, { "Scudo di fuoco II", "Danni da Fuoco a tutti quelli che gli sono vicino per un minuto. Un sacerdote o uno sciamano può rimuoverlo." } }
T[61] = { { "Bombe ambulanti", "Accende una a una le teste di gnomo intorno alla sala, e ognuna sgancia bombe ambulanti che esplodono quando raggiungono un giocatore. Il pulsante accanto a una testa la spegne. Sotto metà salute le accende più in fretta." }, { "Respingere", "Respinge il difensore. Sotto metà salute colpisce tutti quelli intorno a lui." } }
