-- Généré par tools/generate_data.py : ne pas éditer à la main.
local locale = GetLocale()
if locale ~= "ptBR" then return end
local _, NS = ...
NS.Tactics = NS.Tactics or {}
local T = NS.Tactics
T[1] = { { "Maldições e doenças", "Remover uma maldição ou curar uma doença ajuda bastante. Fora isso, é um combate fácil: limpe a sala antes de começar." } }
T[2] = { { "O invocador", "Mate primeiro o invocador: ele traz reforços. Depois o elemental." }, { "Fogo por toda parte", "Dano em área no grupo, pior quando o grupo luta muito no corpo a corpo." } }
T[3] = { { "Arremessado pela sala", "Ele lança os jogadores pela sala. Limpe os grupos mais próximos e tanke-o perto do túnel, para que ninguém caia em outro grupo." } }
T[4] = { { "Medo quando enfraquece", "Quando a vida dele cai, ele aterroriza o grupo inteiro. Leve algo para quebrar o medo, ou limpe a sala antes para que ninguém corra para cima de outros inimigos." }, { "Os cofres fechados", "Após o combate, abra os cofres da sala: cerca de 24 Dwarven Heirlooms para Important Heirlooms, e a tábua de The Treaty of Understanding." } }
T[5] = { { "Nova de Fogo", "Dano de Fogo em todos que estiverem perto dele, várias vezes por combate. Como curador, mantenha o corpo a corpo com a vida cheia." }, { "Gancho de Direita", "Um golpe forte que arremessa o tanque para longe." } }
T[6] = { { "Imolação", "Queima um jogador, depois causa dano de Fogo a cada poucos segundos por 21 segundos. Interrompa a magia ou dissipe a queimadura." }, { "Maldição da Fraqueza", "Reduz o dano físico de um jogador por 30 segundos. Um mago ou druida pode removê-la." } }
T[7] = { { "Atacar Múltiplos", "Atinge seu alvo e o jogador mais próximo dele." } }
T[8] = { { "Veneno", "Os golpes dele envenenam: dano de Natureza ao longo do tempo. Cure o veneno se puder." }, { "Ataque Pérfido", "Dano extra no tanque a cada 5 a 15 segundos." } }
T[9] = { { "As aranhas do pátio", "Nada de especial no próprio chefe. Limpe antes as outras aranhas do pátio, senão elas entram no combate." } }
T[10] = { note = "Limpe o pátio, clique na estátua e resista durante as ondas: ela chega depois.", { "Nova de Gelo", "Dano de Gelo no grupo todo. Se você cura, guarde mana para todas as ondas." } }
T[11] = { { "Arremessado para o alto", "Lança o tanque para o alto e o atordoa por 5 segundos. Cuidado com a ameaça dos jogadores de dano: o tanque só o segura por cerca de metade do combate." }, { "Uma patrulha", "Limpe a sala dele antes de começar: uma patrulha passa por ali. A cabeça dele é coletada para as missões Abominable Creatures e Unending Torment." } }
T[12] = { { "Choque de Chamas", "Sua magia principal. Pode ser interrompida e atordoada: organize interrupções e atordoamentos com o grupo." }, { "Muitos pontos de vida", "O combate mais longo da masmorra. Continue as interrupções até o fim." } }
T[13] = { note = "Limpe a casa e a estátua, clique na lareira e resista durante as ondas. Ele chega depois do último golem de carne.", { "Veneno", "Envenena seu alvo. Fique de olho nas barras de vida." }, { "Golpes poderosos", "Ele bate forte: mantenha o tanque vivo. Leve poções de mana para as ondas antes dele." } }
T[14] = { { "Repulsão", "Ele repele: limpe antes os grupos ao redor dele, senão você cai em um deles." }, { "Escudo Antimagia", "Protege-se por um tempo contra magias." }, { "Golpes poderosos", "Ele bate forte: mantenha o tanque com a vida cheia." } }
T[15] = { { "Rajada de Raios", "Ele mantém distância para lançá-la. Interrompa-o." }, { "Toque Curativo", "Cura a si mesmo ou a um aliado (conjuração de 3 segundos). Interrompa-o." }, { "Forma de Serpente de Cobrahn", "Com 30% de vida, ele se transforma em serpente: golpes mais lentos, porém mais pesados, e começa a fazer jogadores dormirem." } }
T[16] = { { "Toque Curativo", "Cura a si mesma ou a um aliado. Interrompa-a." }, { "Sono", "Faz um jogador dormir por até 20 segundos. Dano o acorda, e uma Dissipar Magia o remove." }, { "Aura de Espinhos", "Dano de Natureza em quem a atacar no corpo a corpo." } }
T[17] = { { "Carapace Escudo", "Por 12 segundos, ele sofre 60% menos dano e ataca mais devagar, porém mais forte." } }
T[18] = { { "Trovoada", "Dano de Natureza em todos que estiverem perto dele, depois ataques e movimento reduzidos por 10 segundos." }, { "Toque Curativo", "Cura a si mesmo ou a um aliado. Interrompa-o." }, { "Sono", "Faz um jogador dormir por até 20 segundos." } }
T[19] = { { "Raios em Cadeia", "Um raio que salta para um segundo jogador. Interrompa-o." } }
T[20] = { { "Toque Curativo", "Uma cura lenta (3,5 segundos) nele ou em um aliado. Interrompa-o." }, { "Sono", "Faz um jogador dormir por até 20 segundos." }, { "Rajada de Raios", "Ele mantém distância para lançá-la. Interrompa-o." } }
T[21] = { { "Vinhas Vorazes", "Quando o alvo dele está por perto, ele derruba e imobiliza todos que estiverem perto dele por 10 segundos. À distância, mantenha a distância." } }
T[22] = { note = "Mate Lady Anacondra, Lorde Cobrahn, Lorde Pythas e Lorde Serpentis, depois fale com o discípulo de Naralex na entrada e escolte-o até Naralex. Proteja-o durante o ritual: Mutanus chega no final.", { "Trovão Estrondoso", "Dano de Natureza em todos que estiverem perto dele e um atordoamento de 2,5 segundos." }, { "Pesadelo de Naralex", "Faz um jogador dormir por até 15 segundos." }, { "Aterrorizar", "Faz um jogador fugir de medo por 4 segundos." } }
T[23] = { { "Golpe de Rhahk'Zor", "Atinge o tanque com força e o atordoa por 3 segundos." } }
T[24] = { { "Perfurar Armadura", "Reduz a armadura do tanque em 75% por 20 segundos." }, { "Foge para buscar ajuda", "Com 15% de vida, ele foge para buscar ajuda. Acabe com ele antes que se afaste." } }
T[25] = { note = "Ele pilota o Triturador do Sneed e sai dele quando é destruído.", { "Desarmar", "Desarma o tanque por 6 segundos." } }
T[26] = { { "Aterrorizar", "Faz um jogador fugir de medo por 4 segundos." }, { "Dor Agonizante", "Reduz a velocidade de conjuração de um jogador em 35% por 15 segundos." } }
T[27] = { { "Metal Derretido", "Dano de Fogo a cada 3 segundos por 15 segundos, com ataques e movimento reduzidos. Interrompa a conjuração de 2 segundos." } }
T[28] = { { "Martelada Violenta", "Com 66% e depois 33% de vida, ele atordoa todos ao redor e vai até seu baú trocar de armas." }, { "Surrar", "Com as duas machadinhas, a partir de 66% de vida: ataques extras no tanque." }, { "Pancada Poderosa", "Com o martelo, abaixo de 33% de vida: um golpe forte que atordoa o tanque por 3 segundos." } }
T[29] = { { "Arpão Envenenado", "Uma conjuração de 2 segundos: um golpe, depois dano de Natureza por um minuto. Cure o veneno." }, { "Atacar Múltiplos", "Atinge seu alvo e o jogador mais próximo dele." } }
T[30] = { { "Surrar", "De tempos em tempos, dois ataques extras: golpes fortes no tanque." }, { "Aliados de VanCleef", "Na metade da vida, ele chama dois Gatunos Defias." } }
T[31] = { { "Jato de Ácido", "Dano de Natureza a cada 5 segundos por 30 segundos em todos que estiverem perto dele." }, { "Culinária do Cookie", "Abaixo de metade da vida, ele se cura (conjuração de 2 segundos). Interrompa-o." }, { "Foge para buscar ajuda", "Com 15% de vida, ele foge para buscar ajuda. Acabe com ele antes que se afaste." } }
T[32] = { { "Drenar Alma", "Imobiliza um jogador por 10 segundos e drena a vida dele para se curar. Interrompa a conjuração de 2 segundos ou dissipe-o." } }
T[33] = { { "Golpe Retorcido", "O corcel vil atordoa todos que estiverem perto dele por 3 segundos, e eles sofrem mais dano físico. O corcel das sombras não tem nenhuma habilidade." } }
T[34] = { { "Drenar do Açougueiro", "Drena 350 pontos de mana do alvo no corpo a corpo: um tanque que tem mana sente a perda." } }
T[35] = { { "Véu das Sombras", "Amaldiçoa um jogador: as curas que ele recebe ficam 75% mais fracas por 15 segundos. Remova-a, principalmente no tanque." } }
T[36] = { { "Luz Sagrada", "Cura a si mesmo ou a um aliado (conjuração de 2,5 segundos). Interrompa-o." }, { "Escudo Divino", "Torna-o imune a todo dano e a todas as magias por 10 segundos." }, { "Martelo da Justiça", "Atordoa um jogador por 4 segundos." } }
T[37] = { { "Pede ajuda", "Quando você o ataca, ele chama as criaturas a até 30 metros. Limpe ao redor dele antes." }, { "Fúria Uivante", "Com 60%, 40% e 20% de vida, os golpes dele ficam mais fortes." } }
T[38] = { { "Atacar Múltiplos", "Atinge seu alvo e o jogador mais próximo dele." }, { "Quebra-joelho", "Reduz a velocidade de movimento do alvo por 10 segundos." } }
T[39] = { note = "Eles chegam em quatro depois da morte de Fenrus, o Devorador: Arugal aparece por um instante e os chama.", { "Oferenda Sombria", "Cura outro andarilho do Vácuo. Matem-nos um por um." } }
T[40] = { { "Baba Tóxica", "Dano de Natureza a cada 6 segundos e mana drenada, por 2 minutos. Cure o veneno." } }
T[41] = { { "Lobos de reforço", "Quanto mais o combate dura, mais lobos ele tem ao lado: um worg pálido após 30 a 45 segundos, depois um worg espumante, depois um horror lupino." } }
T[42] = { { "Seta do Vácuo", "Um projétil de Sombra de 3 segundos no tanque, repetidamente. Interrompa-o." }, { "Maldição de Arugal", "Transforma um jogador que não seja o tanque em um Glutão de Presanegra que luta por ele por 10 segundos. Remova a maldição." }, { "Passo Sombrio", "Ele se teletransporta entre sua plataforma, a plataforma de cima e a escada." }, { "Trovoada", "Quando o tanque chega nele: dano de Natureza e um atordoamento de 5 segundos ao redor dele." } }
T[43] = { { "Pisotear", "Atinge todos que estiverem perto dele." } }
T[44] = { { "Relâmpago Bifurcado", "Dano de Natureza em um cone à frente dela (conjuração de 2 segundos). Fique fora do cone." }, { "Nova de Gelo", "Congela no lugar todos que estiverem perto dela por até 8 segundos." }, { "Lentidão", "Reduz a velocidade de movimento e de ataque de um jogador por 10 segundos." } }
T[45] = { { "Rede", "Imobiliza um jogador no lugar por 10 segundos." } }
T[46] = { note = "Clique na pedra da Brasse na água: ele surge dela.", { "Seta de Gelo", "Ele mantém distância para lançá-la: dano de Gelo e lentidão." }, { "Nova de Gelo", "Imobiliza todos que estiverem perto dele por até 8 segundos." } }
T[47] = { { "Sono", "Faz dormir todos que estiverem perto dele por até 10 segundos. Dano acorda quem dorme." }, { "Ataque Mental", "Dano de Sombra em um jogador (conjuração de 1,5 segundo)." } }
T[48] = { note = "Ele espera em uma caverna submersa, sob o templo do Lorde do Crepúsculo Kelris, e muitos grupos o perdem. Nade sob o templo para chegar até ele." }
T[49] = { note = "Com o Lorde do Crepúsculo Kelris morto, acenda as quatro Chamas de Aku'mai da sala dele, uma após a outra. Cada uma traz uma onda de criaturas. Quando todas estiverem mortas, a porta de Aku'mai se abre.", { "Nuvem Venenosa", "Dano de Natureza a cada 5 segundos por 45 segundos em todos que estiverem por perto." }, { "Fúria Frenética", "Abaixo de 30% de vida: rajadas de ataques 75% mais rápidos, repetidamente." } }
T[50] = { { "Escudo Relâmpago", "Raios atingem quem o tocar. Um sacerdote ou xamã pode removê-lo." }, { "Rajada de Raios", "Ele mantém distância para lançá-la. Interrompa-o." } }
T[51] = { { "Pancada de Escudo", "Atinge o tanque e o atordoa por 2 segundos." }, { "Foge para buscar ajuda", "Com 15% de vida, ele foge para buscar ajuda. Acabe com ele antes que se afaste." } }
T[52] = { { "Foge para buscar ajuda", "Com 15% de vida, ele foge para buscar ajuda. Acabe com ele antes que se afaste." } }
T[53] = { { "Surrar", "De tempos em tempos, dois ataques extras: golpes fortes no tanque." }, { "Enfurecer", "Com 30% de vida, ele ataca 30% mais rápido até o fim do combate." } }
T[54] = { { "Corrente de Raios", "Um raio que salta de jogador em jogador (conjuração de 2 segundos). Interrompa-o." }, { "Sede de Sangue", "Acelera os ataques dele ou de um aliado em 30% por 30 segundos. Um sacerdote ou xamã pode removê-la." } }
T[55] = { { "Bomba de Fumaça", "Atordoa todos que estiverem perto dele por 4 segundos." }, { "Grito de Guerra", "Mais poder de ataque para ele e seus aliados por 2 minutos." }, { "Foge para buscar ajuda", "Com 15% de vida, ele foge para buscar ajuda. Acabe com ele antes que se afaste." } }
T[56] = { { "Rede", "Imobiliza todos que estiverem perto dele por 10 segundos." }, { "Lentidão", "Reduz a velocidade de ataque e de movimento de um jogador por 10 segundos, e pode atordoá-lo." }, { "Invocar Barata Mecânica", "Chama baratas mecânicas. A Atualização dele as mata e o cura." } }
T[57] = { note = "Fale com a especialista em demolição Emi Shortfuse e proteja-a enquanto ela explode as duas entradas da caverna. Troggs chegam em ondas, depois Grubbis vem com Chomper." }
T[58] = { { "Megavolt", "Dano de Natureza em um cone à frente dele (conjuração de 2 segundos). Só o tanque fica à frente." }, { "Corrente de Raios", "Um raio que salta entre jogadores próximos (conjuração de 2,5 segundos). Interrompa-o." } }
T[59] = { { "Ceifar Multidão", "Atinge todos que estiverem perto dele e interrompe suas magias. Conjuradores e curadores, mantenham distância." }, { "Golpe Varredor", "Atinge todos em um cone à frente dele." }, { "Pisotear", "Atinge todos que estiverem perto dele." } }
T[60] = { { "Invocar Servo Flamejante", "Chama dois servos flamejantes no início do combate." }, { "Bola de Fogo", "Ele mantém distância para lançá-la. Interrompa-o." }, { "Escudo de Fogo II", "Dano de Fogo em todos que estiverem perto dele por um minuto. Um sacerdote ou xamã pode removê-lo." } }
T[61] = { { "Bombas Ambulantes", "Ele acende uma a uma as cabeças de gnomo ao redor da sala, e cada uma solta bombas ambulantes que explodem ao alcançar um jogador. O botão ao lado de uma cabeça a apaga. Abaixo de metade da vida, ele as acende mais rápido." }, { "Repelir", "Arremessa o tanque para longe. Abaixo de metade da vida, atinge todos ao redor dele." } }
